<?php

// Simple Google scholar search to get RIS from title.
//
// To get RIS format add ":CF=2" to GSP ID= field in cookie.txt
// e.g. 
//.scholar.google.com	TRUE	/	FALSE	2147483647	GSP	ID=353e8f974d766dcd:CF=2

require_once(dirname(__FILE__) . '/config.inc.php');
require_once(dirname(__FILE__) . '/ris.php');

/*

 Need a cookie file (scholar_cookie.txt) like this:

# Netscape HTTP Cookie File
# http://curlm.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.

.scholar.google.com	TRUE	/	FALSE	2147483647	GSP	ID=353e8f974d766dcd:CF=2
.google.com	TRUE	/	FALSE	1317124758	PREF	ID=353e8f974d766dcd:TM=1254052758:LM=1254052758:S=_biVh02e4scrJT1H
.scholar.google.co.uk	TRUE	/	FALSE	2147483647	GSP	ID=f3f18b3b5a7c2647:CF=2
.google.co.uk	TRUE	/	FALSE	1317125123	PREF	ID=f3f18b3b5a7c2647:TM=1254053123:LM=1254053123:S=UqjRcTObh7_sARkN

*/

$title = $_GET['title'];

$store = 0;
if (isset($_GET['store']))
{
	$store = 1;
}


//$title = 'Biomagnification of cycad neurotoxins in flying foxes Implications for ALS-PDC in Guam';



$title = strip_tags($title);

$url = 'http://scholar.google.co.uk';

$url .= '/scholar';
//$url .= "?q=allintitle:";
$url .= "?q=";
$url .= str_replace(' ', '+', $title);
$url .= "&amp;ie=UTF-8";
$url .= "&amp;oe=UTF-8";
$url .= "&amp;hl=en";
$url .= "&amp;num=10";

//echo $url;

$ch = curl_init(); 
curl_setopt ($ch, CURLOPT_URL, $url); 
curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt ($ch, CURLOPT_FOLLOWLOCATION,	1); 
curl_setopt ($ch, CURLOPT_COOKIEJAR, 'scholar_cookie.txt');
curl_setopt ($ch, CURLOPT_COOKIEFILE, 'scholar_cookie.txt');
curl_setopt ($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.0.14) Gecko/2009082706 Firefox/3.0.14');
curl_setopt ($ch, CURLOPT_REFERER, 'http://scholar.google.co.uk/scholar?q=flying+foxes&hl=en&btnG=Search');


if ($config['proxy_name'] != '')
{
	curl_setopt ($ch, CURLOPT_PROXY, $config['proxy_name'] . ':' . $config['proxy_port']);
}

$html=curl_exec ($ch); 

if( curl_errno ($ch) != 0 )
{
}

//$info = curl_getinfo($ch);
//print_r($info);

// Clean
$html = preg_replace('/<font size=-2 class="w"><b>\[PDF\]<\/b><\/font>&nbsp;<span class=a>&#x25ba;<\/span>/', '', $html);
$html = preg_replace('/<span class=a>&#x25ba;<\/span>/', '', $html);

$html = str_replace("\n", " ", $html);

//echo $html;	

//exit();

$title_url = '';

// get URLs
if (preg_match('/<h3 class="r"><a href="(?<url>([^"]|(?R))*)/', $html, $matches))
{
	$title_url = $matches['url'];
}

// get RIS
if (preg_match('/<a href="\/scholar.ris\?(?<q>.*)">Import into RefMan<\/a>/Uu', $html, $matches))
{
	//print_r($matches);
	
	$url = 'http://scholar.google.com/scholar.ris?' . str_replace('&amp;', '&', $matches['q']);
	
	//echo $url;
	
	curl_setopt($ch, CURLOPT_URL, $url); 
	$ris=curl_exec ($ch); 
	
	if( curl_errno ($ch) != 0 )
	{
	}
	
	$ris = str_replace ("\r\nER", "\r\nUR  - $title_url\r\nER", $ris);
	$ris = utf8_encode($ris);
	
	header("Content-type: text/plain; charset=utf-8\n\n");	
	echo $ris;	
	
	if (preg_match('/TY  \- JOUR/', $ris))
	{
		if ($store)
		{
			import_ris($ris);
			echo "\r\nStored\r\n";
		}
	}
	
}

?>